// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsqJcfs2q8hwOOuGUO2rhj9BHcNbJjIxk',
    appId: '1:1013973377953:web:8f0156407a7df5829c61e0',
    messagingSenderId: '1013973377953',
    projectId: 'mllearning-6520a',
    authDomain: 'mllearning-6520a.firebaseapp.com',
    storageBucket: 'mllearning-6520a.appspot.com',
    measurementId: 'G-YHLZ0WV614',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfr96r7QAxy5Wymf04bJKZzm3cSCp7aOY',
    appId: '1:1013973377953:android:52d5770909dd891a9c61e0',
    messagingSenderId: '1013973377953',
    projectId: 'mllearning-6520a',
    storageBucket: 'mllearning-6520a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXI8ASH4A-XFdBonK-9KY2AyUL-FaxA0o',
    appId: '1:1013973377953:ios:b9e17b3ba2af86bf9c61e0',
    messagingSenderId: '1013973377953',
    projectId: 'mllearning-6520a',
    storageBucket: 'mllearning-6520a.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXI8ASH4A-XFdBonK-9KY2AyUL-FaxA0o',
    appId: '1:1013973377953:ios:3eab833a5d8d17129c61e0',
    messagingSenderId: '1013973377953',
    projectId: 'mllearning-6520a',
    storageBucket: 'mllearning-6520a.appspot.com',
    iosBundleId: 'com.example.untitled.RunnerTests',
  );
}
